package gosdk

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/infrasutra/fsl/parser"
	"github.com/infrasutra/fsl/sdk"
)

type Generator struct{}

func New() *Generator {
	return &Generator{}
}

func (g *Generator) Language() string {
	return "go"
}

func (g *Generator) FileExtension() string {
	return ".go"
}

func (g *Generator) Generate(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (*sdk.GeneratedSDK, error) {
	output := &sdk.GeneratedSDK{
		Language:   "go",
		Files:      make(map[string]string),
		EntryPoint: "client.go",
	}

	models, err := g.generateModels(schemas, config)
	if err != nil {
		return nil, fmt.Errorf("failed to generate models: %w", err)
	}
	output.Files["models.go"] = models

	if config.IncludeClient {
		client, err := g.generateClient(schemas, config)
		if err != nil {
			return nil, fmt.Errorf("failed to generate client: %w", err)
		}
		output.Files["client.go"] = client
	}

	return output, nil
}

func (g *Generator) generateModels(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	var buf bytes.Buffer

	packageName := config.PackageName
	if packageName == "" {
		packageName = "client"
	}

	buf.WriteString("// Generated by Flux CMS SDK Generator\n")
	buf.WriteString(fmt.Sprintf("// Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	buf.WriteString("// DO NOT EDIT - This file is auto-generated\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))
	buf.WriteString("import \"time\"\n\n")

	buf.WriteString(g.builtInTypes())
	buf.WriteString("\n")
	buf.WriteString(g.sharedResponseTypes())
	buf.WriteString("\n")

	for _, schema := range schemas {
		for _, enum := range schema.Enums {
			buf.WriteString(g.generateEnumType(&enum))
			buf.WriteString("\n")
		}
		buf.WriteString(g.generateInlineEnums(schema))
		buf.WriteString(g.generateSliceSupportTypes(schema))
	}

	for _, schema := range schemas {
		buf.WriteString(g.generateStruct(schema))
		buf.WriteString("\n")
		buf.WriteString(g.generateCreateInput(schema))
		buf.WriteString("\n")
		buf.WriteString(g.generateUpdateInput(schema))
		buf.WriteString("\n")
		buf.WriteString(g.generateFilterType(schema, config.TargetAPI))
		buf.WriteString("\n")
		buf.WriteString(g.generateSchemaAliases(schema))
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

func (g *Generator) generateClient(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	var buf bytes.Buffer

	packageName := config.PackageName
	if packageName == "" {
		packageName = "client"
	}

	baseURL := config.BaseURL
	if baseURL == "" {
		baseURL = "http://localhost:7080"
	}

	buf.WriteString("// Generated by Flux CMS SDK Generator\n")
	buf.WriteString(fmt.Sprintf("// Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	buf.WriteString("// DO NOT EDIT - This file is auto-generated\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"io\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"net/url\"\n")
	buf.WriteString("\t\"strings\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("type ClientConfig struct {\n")
	buf.WriteString("\tBaseURL string\n")
	buf.WriteString("\tAPIKey string\n")
	buf.WriteString("\tHeaders map[string]string\n")
	buf.WriteString("\tHTTPClient *http.Client\n")
	buf.WriteString("}\n\n")

	if config.TargetAPI == "content" {
		buf.WriteString("type FluxClient struct {\n")
		buf.WriteString("\tbaseURL string\n")
		buf.WriteString("\theaders map[string]string\n")
		buf.WriteString("\thttpClient *http.Client\n")
		buf.WriteString("\tworkspaceAPIID string\n")
		buf.WriteString("}\n\n")

		buf.WriteString("func NewFluxClient(config ClientConfig, workspaceAPIID string) *FluxClient {\n")
		buf.WriteString("\tbaseURL := config.BaseURL\n")
		buf.WriteString(fmt.Sprintf("\tif baseURL == \"\" {\n\t\tbaseURL = \"%s\"\n\t}\n", baseURL))
		buf.WriteString("\theaders := map[string]string{}\n")
		buf.WriteString("\tfor k, v := range config.Headers {\n")
		buf.WriteString("\t\theaders[k] = v\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tif config.APIKey != \"\" {\n")
		buf.WriteString("\t\theaders[\"X-API-Key\"] = config.APIKey\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\thttpClient := config.HTTPClient\n")
		buf.WriteString("\tif httpClient == nil {\n")
		buf.WriteString("\t\thttpClient = &http.Client{}\n")
		buf.WriteString("\t}\n")
		buf.WriteString(fmt.Sprintf("\tif workspaceAPIID == \"\" {\n\t\tworkspaceAPIID = \"%s\"\n\t}\n", config.WorkspaceAPIID))
		buf.WriteString("\treturn &FluxClient{\n")
		buf.WriteString("\t\tbaseURL: strings.TrimRight(baseURL, \"/\"),\n")
		buf.WriteString("\t\theaders: headers,\n")
		buf.WriteString("\t\thttpClient: httpClient,\n")
		buf.WriteString("\t\tworkspaceAPIID: workspaceAPIID,\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	} else {
		buf.WriteString("type FluxClient struct {\n")
		buf.WriteString("\tbaseURL string\n")
		buf.WriteString("\theaders map[string]string\n")
		buf.WriteString("\thttpClient *http.Client\n")
		buf.WriteString("\tprojectID string\n")
		buf.WriteString("}\n\n")

		buf.WriteString("func NewFluxClient(config ClientConfig, projectID string) *FluxClient {\n")
		buf.WriteString("\tbaseURL := config.BaseURL\n")
		buf.WriteString(fmt.Sprintf("\tif baseURL == \"\" {\n\t\tbaseURL = \"%s\"\n\t}\n", baseURL))
		buf.WriteString("\theaders := map[string]string{}\n")
		buf.WriteString("\tfor k, v := range config.Headers {\n")
		buf.WriteString("\t\theaders[k] = v\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tif config.APIKey != \"\" {\n")
		buf.WriteString("\t\theaders[\"Authorization\"] = \"Bearer \" + config.APIKey\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\thttpClient := config.HTTPClient\n")
		buf.WriteString("\tif httpClient == nil {\n")
		buf.WriteString("\t\thttpClient = &http.Client{}\n")
		buf.WriteString("\t}\n")
		buf.WriteString(fmt.Sprintf("\tif projectID == \"\" {\n\t\tprojectID = \"%s\"\n\t}\n", config.ProjectID))
		buf.WriteString("\treturn &FluxClient{\n")
		buf.WriteString("\t\tbaseURL: strings.TrimRight(baseURL, \"/\"),\n")
		buf.WriteString("\t\theaders: headers,\n")
		buf.WriteString("\t\thttpClient: httpClient,\n")
		buf.WriteString("\t\tprojectID: projectID,\n")
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	buf.WriteString("func (c *FluxClient) request(ctx context.Context, method, path string, body any, out any) error {\n")
	buf.WriteString("\tvar requestBody io.Reader\n")
	buf.WriteString("\tif body != nil {\n")
	buf.WriteString("\t\tencoded, err := json.Marshal(body)\n")
	buf.WriteString("\t\tif err != nil {\n")
	buf.WriteString("\t\t\treturn fmt.Errorf(\"marshal request body: %w\", err)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\trequestBody = bytes.NewReader(encoded)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treq, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, requestBody)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"build request: %w\", err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tfor k, v := range c.headers {\n")
	buf.WriteString("\t\treq.Header.Set(k, v)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif body != nil {\n")
	buf.WriteString("\t\treq.Header.Set(\"Content-Type\", \"application/json\")\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tresp, err := c.httpClient.Do(req)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"send request: %w\", err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer resp.Body.Close()\n")
	buf.WriteString("\traw, err := io.ReadAll(resp.Body)\n")
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"read response: %w\", err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif resp.StatusCode < 200 || resp.StatusCode >= 300 {\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"request failed %s %s: status %d body %s\", method, path, resp.StatusCode, strings.TrimSpace(string(raw)))\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif out == nil || len(raw) == 0 {\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tvar envelope struct {\n")
	buf.WriteString("\t\tPayload json.RawMessage `json:\"payload\"`\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif err := json.Unmarshal(raw, &envelope); err == nil && len(envelope.Payload) > 0 {\n")
	buf.WriteString("\t\tif err := json.Unmarshal(envelope.Payload, out); err != nil {\n")
	buf.WriteString("\t\t\treturn fmt.Errorf(\"decode payload: %w\", err)\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\treturn nil\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif err := json.Unmarshal(raw, out); err != nil {\n")
	buf.WriteString("\t\treturn fmt.Errorf(\"decode response: %w\", err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn nil\n")
	buf.WriteString("}\n\n")

	if config.TargetAPI == "content" {
		for _, schema := range schemas {
			typeName := ToPascalCase(schema.Name)
			apiID := schema.ApiID

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) List%s(ctx context.Context, filter *%sFilter) (*%sContentListResponse, error) {\n", typeName, typeName, typeName))
			buf.WriteString("\tparams := url.Values{}\n")
			buf.WriteString("\tif filter != nil {\n")
			buf.WriteString("\t\tif filter.Page != nil {\n\t\t\tparams.Set(\"page\", fmt.Sprintf(\"%d\", *filter.Page))\n\t\t}\n")
			buf.WriteString("\t\tif filter.PerPage != nil {\n\t\t\tparams.Set(\"per_page\", fmt.Sprintf(\"%d\", *filter.PerPage))\n\t\t}\n")
			buf.WriteString("\t\tif filter.Locale != nil {\n\t\t\tparams.Set(\"locale\", *filter.Locale)\n\t\t}\n")
			buf.WriteString("\t\tif filter.CreatedAfter != nil {\n\t\t\tparams.Set(\"created_after\", *filter.CreatedAfter)\n\t\t}\n")
			buf.WriteString("\t\tif filter.CreatedBefore != nil {\n\t\t\tparams.Set(\"created_before\", *filter.CreatedBefore)\n\t\t}\n")
			buf.WriteString("\t\tif filter.SortBy != nil {\n\t\t\tparams.Set(\"sort_by\", *filter.SortBy)\n\t\t}\n")
			buf.WriteString("\t\tif filter.SortOrder != nil {\n\t\t\tparams.Set(\"sort_order\", *filter.SortOrder)\n\t\t}\n")
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\tpath := fmt.Sprintf(\"/api/v1/content/%%s/%s\", c.workspaceAPIID)\n", apiID))
			buf.WriteString("\tif encoded := params.Encode(); encoded != \"\" {\n")
			buf.WriteString("\t\tpath += \"?\" + encoded\n")
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\tvar out %sContentListResponse\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodGet, path, nil, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Get%sBySlug(ctx context.Context, slug string) (*%sContentItem, error) {\n", typeName, typeName))
			buf.WriteString(fmt.Sprintf("\tpath := fmt.Sprintf(\"/api/v1/content/%%s/%s/%%s\", c.workspaceAPIID, url.PathEscape(slug))\n", apiID))
			buf.WriteString(fmt.Sprintf("\tvar out %sContentItem\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodGet, path, nil, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Get%sByID(ctx context.Context, id string) (*%sContentItem, error) {\n", typeName, typeName))
			buf.WriteString(fmt.Sprintf("\tpath := fmt.Sprintf(\"/api/v1/content/%%s/%s/id/%%s\", c.workspaceAPIID, url.PathEscape(id))\n", apiID))
			buf.WriteString(fmt.Sprintf("\tvar out %sContentItem\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodGet, path, nil, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")
		}
	} else {
		buf.WriteString("type CreateOptions struct {\n")
		buf.WriteString("\tSlug *string `json:\"slug,omitempty\"`\n")
		buf.WriteString("\tLocale *string `json:\"locale,omitempty\"`\n")
		buf.WriteString("\tMessage *string `json:\"message,omitempty\"`\n")
		buf.WriteString("}\n\n")
		buf.WriteString("type UpdateOptions struct {\n")
		buf.WriteString("\tSlug *string `json:\"slug,omitempty\"`\n")
		buf.WriteString("\tMessage *string `json:\"message,omitempty\"`\n")
		buf.WriteString("}\n\n")

		for _, schema := range schemas {
			typeName := ToPascalCase(schema.Name)
			apiID := schema.ApiID
			schemaID := schema.SchemaID

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Get%s(ctx context.Context, id string) (*%sDocument, error) {\n", typeName, typeName))
			buf.WriteString("\tpath := fmt.Sprintf(\"/api/v1/cms/projects/%s/documents/%s\", c.projectID, url.PathEscape(id))\n")
			buf.WriteString(fmt.Sprintf("\tvar out %sDocument\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodGet, path, nil, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) List%s(ctx context.Context, filter *%sFilter) (*%sListResponse, error) {\n", typeName, typeName, typeName))
			buf.WriteString("\tparams := url.Values{}\n")
			buf.WriteString("\tif filter != nil {\n")
			buf.WriteString("\t\tif filter.Limit != nil {\n\t\t\tparams.Set(\"limit\", fmt.Sprintf(\"%d\", *filter.Limit))\n\t\t}\n")
			buf.WriteString("\t\tif filter.Offset != nil {\n\t\t\tparams.Set(\"offset\", fmt.Sprintf(\"%d\", *filter.Offset))\n\t\t}\n")
			buf.WriteString("\t\tif filter.Status != nil {\n\t\t\tparams.Set(\"status\", *filter.Status)\n\t\t}\n")
			buf.WriteString("\t\tif filter.Sort != nil {\n\t\t\tparams.Set(\"sort\", *filter.Sort)\n\t\t}\n")
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\tpath := fmt.Sprintf(\"/api/v1/cms/projects/%%s/schemas/%s/documents\", c.projectID)\n", schemaID))
			buf.WriteString("\tif encoded := params.Encode(); encoded != \"\" {\n")
			buf.WriteString("\t\tpath += \"?\" + encoded\n")
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\tvar out %sListResponse\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodGet, path, nil, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Create%s(ctx context.Context, data Create%sInput, options *CreateOptions) (*%sDocument, error) {\n", typeName, typeName, typeName))
			buf.WriteString("\tbody := map[string]any{\n")
			buf.WriteString("\t\t\"data\": data,\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\tif options != nil {\n")
			buf.WriteString("\t\tif options.Slug != nil { body[\"slug\"] = *options.Slug }\n")
			buf.WriteString("\t\tif options.Locale != nil { body[\"locale\"] = *options.Locale }\n")
			buf.WriteString("\t\tif options.Message != nil { body[\"message\"] = *options.Message }\n")
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\tpath := fmt.Sprintf(\"/api/v1/cms/projects/%%s/schemas/%s/documents\", c.projectID)\n", schemaID))
			buf.WriteString(fmt.Sprintf("\tvar out %sDocument\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodPost, path, body, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Update%s(ctx context.Context, id string, data Update%sInput, options *UpdateOptions) (*%sDocument, error) {\n", typeName, typeName, typeName))
			buf.WriteString("\tbody := map[string]any{\n")
			buf.WriteString("\t\t\"data\": data,\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\tif options != nil {\n")
			buf.WriteString("\t\tif options.Slug != nil { body[\"slug\"] = *options.Slug }\n")
			buf.WriteString("\t\tif options.Message != nil { body[\"message\"] = *options.Message }\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\tpath := fmt.Sprintf(\"/api/v1/cms/projects/%s/documents/%s\", c.projectID, url.PathEscape(id))\n")
			buf.WriteString(fmt.Sprintf("\tvar out %sDocument\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodPut, path, body, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Delete%s(ctx context.Context, id string) error {\n", typeName))
			buf.WriteString("\tpath := fmt.Sprintf(\"/api/v1/cms/projects/%s/documents/%s\", c.projectID, url.PathEscape(id))\n")
			buf.WriteString("\treturn c.request(ctx, http.MethodDelete, path, nil, nil)\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Publish%s(ctx context.Context, id string) (*%sDocument, error) {\n", typeName, typeName))
			buf.WriteString("\tpath := fmt.Sprintf(\"/api/v1/cms/projects/%s/documents/%s/publish\", c.projectID, url.PathEscape(id))\n")
			buf.WriteString(fmt.Sprintf("\tvar out %sDocument\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodPost, path, nil, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			buf.WriteString(fmt.Sprintf("func (c *FluxClient) Archive%s(ctx context.Context, id string) (*%sDocument, error) {\n", typeName, typeName))
			buf.WriteString("\tpath := fmt.Sprintf(\"/api/v1/cms/projects/%s/documents/%s/archive\", c.projectID, url.PathEscape(id))\n")
			buf.WriteString(fmt.Sprintf("\tvar out %sDocument\n", typeName))
			buf.WriteString("\tif err := c.request(ctx, http.MethodPost, path, nil, &out); err != nil {\n")
			buf.WriteString("\t\treturn nil, err\n")
			buf.WriteString("\t}\n")
			buf.WriteString("\treturn &out, nil\n")
			buf.WriteString("}\n\n")

			_ = apiID
		}
	}

	return buf.String(), nil
}

func (g *Generator) generateEnumType(enum *parser.CompiledEnum) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(enum.Name)
	buf.WriteString(fmt.Sprintf("type %s string\n\n", typeName))
	buf.WriteString("const (\n")
	for _, value := range enum.Values {
		constName := typeName + sanitizeIdentifier(value)
		buf.WriteString(fmt.Sprintf("\t%s %s = %q\n", constName, typeName, value))
	}
	buf.WriteString(")\n")

	return buf.String()
}

func (g *Generator) generateInlineEnums(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	for _, field := range schema.Fields {
		if field.Type != "Enum" || len(field.InlineEnum) == 0 {
			continue
		}

		typeName := g.inlineEnumTypeName(schema, &field)
		buf.WriteString(fmt.Sprintf("type %s string\n\n", typeName))
		buf.WriteString("const (\n")
		for _, value := range field.InlineEnum {
			buf.WriteString(fmt.Sprintf("\t%s%s %s = %q\n", typeName, sanitizeIdentifier(value), typeName, value))
		}
		buf.WriteString(")\n\n")
	}

	return buf.String()
}

func (g *Generator) generateSliceSupportTypes(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	componentByName := make(map[string]*parser.CompiledComponent, len(schema.Components))
	for i := range schema.Components {
		component := &schema.Components[i]
		componentByName[component.Name] = component
	}

	emittedComponents := map[string]bool{}

	for _, field := range schema.Fields {
		if len(field.Slices) == 0 {
			continue
		}

		for _, slice := range field.Slices {
			component, ok := componentByName[slice.Schema]
			if !ok {
				continue
			}

			componentTypeName := g.sliceComponentTypeName(schema, slice.Schema)
			if emittedComponents[componentTypeName] {
				continue
			}

			emittedComponents[componentTypeName] = true
			buf.WriteString(fmt.Sprintf("type %s struct {\n", componentTypeName))
			for _, componentField := range component.Fields {
				fieldName := ToPascalCase(componentField.Name)
				fieldType := g.mapFieldType(schema, &componentField, false, false, false)
				tag := "`json:\"" + componentField.Name
				if !componentField.Required && !componentField.ArrayReq {
					tag += ",omitempty"
				}
				tag += "\"`"
				buf.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, tag))
			}
			buf.WriteString("}\n\n")
		}

		unionTypeName := g.sliceUnionTypeName(schema, &field)
		buf.WriteString(fmt.Sprintf("type %s struct {\n", unionTypeName))
		buf.WriteString("\tType string `json:\"type\"`\n")
		buf.WriteString("\tVariation *string `json:\"variation,omitempty\"`\n")
		buf.WriteString("\tData map[string]any `json:\"data\"`\n")
		buf.WriteString("}\n\n")
	}

	return buf.String()
}

func (g *Generator) generateStruct(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("type %s struct {\n", typeName))

	for _, field := range schema.Fields {
		fieldName := ToPascalCase(field.Name)
		fieldType := g.mapFieldType(schema, &field, false, false, false)
		tag := "`json:\"" + field.Name
		if !field.Required && !field.ArrayReq {
			tag += ",omitempty"
		}
		tag += "\"`"
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, tag))
	}

	buf.WriteString("}\n")
	return buf.String()
}

func (g *Generator) generateCreateInput(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("type Create%sInput struct {\n", typeName))

	for _, field := range schema.Fields {
		fieldName := ToPascalCase(field.Name)
		fieldType := g.mapFieldType(schema, &field, true, false, false)
		tag := "`json:\"" + field.Name
		if !field.Required && !field.ArrayReq {
			tag += ",omitempty"
		}
		tag += "\"`"
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, tag))
	}

	buf.WriteString("}\n")
	return buf.String()
}

func (g *Generator) generateUpdateInput(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("type Update%sInput struct {\n", typeName))

	for _, field := range schema.Fields {
		fieldName := ToPascalCase(field.Name)
		fieldType := g.mapFieldType(schema, &field, true, true, false)
		tag := "`json:\"" + field.Name + ",omitempty\"`"
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, tag))
	}

	buf.WriteString("}\n")
	return buf.String()
}

func (g *Generator) generateFilterType(schema *parser.CompiledSchema, targetAPI string) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("type %sFilter struct {\n", typeName))

	if targetAPI == "cms" {
		buf.WriteString("\tLimit *int `json:\"limit,omitempty\"`\n")
		buf.WriteString("\tOffset *int `json:\"offset,omitempty\"`\n")
		buf.WriteString("\tStatus *string `json:\"status,omitempty\"`\n")
		buf.WriteString("\tSort *string `json:\"sort,omitempty\"`\n")
	} else {
		buf.WriteString("\tPage *int `json:\"page,omitempty\"`\n")
		buf.WriteString("\tPerPage *int `json:\"per_page,omitempty\"`\n")
		buf.WriteString("\tLocale *string `json:\"locale,omitempty\"`\n")
		buf.WriteString("\tCreatedAfter *string `json:\"created_after,omitempty\"`\n")
		buf.WriteString("\tCreatedBefore *string `json:\"created_before,omitempty\"`\n")
		buf.WriteString("\tSortBy *string `json:\"sort_by,omitempty\"`\n")
		buf.WriteString("\tSortOrder *string `json:\"sort_order,omitempty\"`\n")
	}

	buf.WriteString("}\n")
	return buf.String()
}

func (g *Generator) generateSchemaAliases(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("type %sDocument = DocumentResponse[%s]\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("type %sListResponse = DocumentListResponse\n", typeName))
	buf.WriteString(fmt.Sprintf("type %sContentItem = ContentItem[%s]\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("type %sContentListResponse = ContentListResponse[%s]\n", typeName, typeName))

	return buf.String()
}

func (g *Generator) mapFieldType(schema *parser.CompiledSchema, field *parser.CompiledField, inputMode, forceOptional, component bool) string {
	baseType := g.mapBaseType(schema, field, inputMode, component)

	if len(field.Slices) > 0 {
		baseType = "[]" + g.sliceUnionTypeName(schema, field)
	}

	if field.Array {
		if strings.HasPrefix(baseType, "[]") {
			if forceOptional || (!field.ArrayReq && !field.Required) {
				return "*" + baseType
			}
			return baseType
		}

		arrayType := "[]" + baseType
		if forceOptional || (!field.ArrayReq && !field.Required) {
			return "*" + arrayType
		}
		return arrayType
	}

	if forceOptional || (!field.Required && !field.ArrayReq) {
		return pointerType(baseType)
	}

	return baseType
}

func pointerType(baseType string) string {
	if strings.HasPrefix(baseType, "*") {
		return baseType
	}
	return "*" + baseType
}

func (g *Generator) mapBaseType(schema *parser.CompiledSchema, field *parser.CompiledField, inputMode, component bool) string {
	if len(field.Slices) > 0 {
		return g.sliceUnionTypeName(schema, field)
	}

	if field.IsRelation {
		if inputMode {
			return "string"
		}
		return ToPascalCase(field.RelationTo)
	}

	if field.Type == "Enum" && len(field.InlineEnum) > 0 {
		if component {
			return "string"
		}
		return g.inlineEnumTypeName(schema, field)
	}

	if mapped, ok := TypeMapping[field.Type]; ok {
		if field.Type == "Enum" {
			return ToPascalCase(field.Type)
		}
		return mapped
	}

	for _, enum := range schema.Enums {
		if enum.Name == field.Type {
			return ToPascalCase(enum.Name)
		}
	}

	return ToPascalCase(field.Type)
}

func (g *Generator) inlineEnumTypeName(schema *parser.CompiledSchema, field *parser.CompiledField) string {
	return ToPascalCase(schema.Name) + ToPascalCase(field.Name)
}

func (g *Generator) sliceUnionTypeName(schema *parser.CompiledSchema, field *parser.CompiledField) string {
	return ToPascalCase(schema.Name) + ToPascalCase(field.Name) + "Slice"
}

func (g *Generator) sliceComponentTypeName(schema *parser.CompiledSchema, componentName string) string {
	return ToPascalCase(schema.Name) + ToPascalCase(componentName)
}

func (g *Generator) builtInTypes() string {
	return `type ImageAsset struct {
	URL string ` + "`json:\"url\"`" + `
	Width *int ` + "`json:\"width,omitempty\"`" + `
	Height *int ` + "`json:\"height,omitempty\"`" + `
	Alt *string ` + "`json:\"alt,omitempty\"`" + `
	Filename *string ` + "`json:\"filename,omitempty\"`" + `
	Size *int64 ` + "`json:\"size,omitempty\"`" + `
	MimeType *string ` + "`json:\"mime_type,omitempty\"`" + `
}

type FileAsset struct {
	URL string ` + "`json:\"url\"`" + `
	Filename *string ` + "`json:\"filename,omitempty\"`" + `
	Size *int64 ` + "`json:\"size,omitempty\"`" + `
	MimeType *string ` + "`json:\"mime_type,omitempty\"`" + `
}

type RichTextBlock map[string]any
`
}

func (g *Generator) sharedResponseTypes() string {
	return `type SchemaRef struct {
	ID *string ` + "`json:\"id,omitempty\"`" + `
	APIID string ` + "`json:\"api_id\"`" + `
	Name string ` + "`json:\"name\"`" + `
}

type PaginationInfo struct {
	Total int ` + "`json:\"total\"`" + `
	Page int ` + "`json:\"page\"`" + `
	Limit int ` + "`json:\"limit\"`" + `
	TotalPages int ` + "`json:\"total_pages\"`" + `
	HasNext bool ` + "`json:\"has_next\"`" + `
	HasPrevious bool ` + "`json:\"has_previous\"`" + `
}

type UserRef struct {
	ID string ` + "`json:\"id\"`" + `
	Name string ` + "`json:\"name\"`" + `
}

type DocumentResponse[T any] struct {
	ID string ` + "`json:\"id\"`" + `
	WorkspaceID string ` + "`json:\"workspace_id\"`" + `
	Schema SchemaRef ` + "`json:\"schema\"`" + `
	Slug *string ` + "`json:\"slug,omitempty\"`" + `
	Locale string ` + "`json:\"locale\"`" + `
	Data T ` + "`json:\"data\"`" + `
	Status string ` + "`json:\"status\"`" + `
	CurrentCommit string ` + "`json:\"current_commit\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\"`" + `
	PublishedAt *time.Time ` + "`json:\"published_at,omitempty\"`" + `
	ScheduledAt *time.Time ` + "`json:\"scheduled_at,omitempty\"`" + `
	CreatedBy *UserRef ` + "`json:\"created_by,omitempty\"`" + `
	UpdatedBy *UserRef ` + "`json:\"updated_by,omitempty\"`" + `
}

type DocumentListItem struct {
	ID string ` + "`json:\"id\"`" + `
	Slug *string ` + "`json:\"slug,omitempty\"`" + `
	Locale string ` + "`json:\"locale\"`" + `
	Status string ` + "`json:\"status\"`" + `
	CurrentCommit string ` + "`json:\"current_commit\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\"`" + `
	PublishedAt *time.Time ` + "`json:\"published_at,omitempty\"`" + `
	ScheduledAt *time.Time ` + "`json:\"scheduled_at,omitempty\"`" + `
}

type DocumentListResponse struct {
	Documents []DocumentListItem ` + "`json:\"documents\"`" + `
	Pagination PaginationInfo ` + "`json:\"pagination\"`" + `
}

type ContentItem[T any] struct {
	ID string ` + "`json:\"id\"`" + `
	Slug *string ` + "`json:\"slug,omitempty\"`" + `
	Locale string ` + "`json:\"locale\"`" + `
	Data T ` + "`json:\"data\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\"`" + `
	PublishedAt time.Time ` + "`json:\"published_at\"`" + `
	Schema SchemaRef ` + "`json:\"schema\"`" + `
}

type ContentListResponse[T any] struct {
	Data []ContentItem[T] ` + "`json:\"data\"`" + `
	Pagination PaginationInfo ` + "`json:\"pagination\"`" + `
	Schema SchemaRef ` + "`json:\"schema\"`" + `
}
`
}
