package python

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/infrasutra/fsl/parser"
	"github.com/infrasutra/fsl/sdk"
)

// Generator implements SDK code generation for Python
type Generator struct{}

// New creates a new Python generator
func New() *Generator {
	return &Generator{}
}

// Language returns the target language name
func (g *Generator) Language() string {
	return "python"
}

// FileExtension returns the file extension for generated files
func (g *Generator) FileExtension() string {
	return ".py"
}

// Generate produces Python SDK code from compiled schemas
func (g *Generator) Generate(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (*sdk.GeneratedSDK, error) {
	output := &sdk.GeneratedSDK{
		Language:   "python",
		Files:      make(map[string]string),
		EntryPoint: "__init__.py",
	}

	// Generate models file
	modelsContent, err := g.generateModels(schemas, config)
	if err != nil {
		return nil, fmt.Errorf("failed to generate models: %w", err)
	}
	output.Files["models.py"] = modelsContent

	// Generate client file if requested
	if config.IncludeClient {
		clientContent, err := g.generateClient(schemas, config)
		if err != nil {
			return nil, fmt.Errorf("failed to generate client: %w", err)
		}
		output.Files["client.py"] = clientContent
	}

	// Generate __init__.py
	initContent := g.generateInit(config)
	output.Files["__init__.py"] = initContent

	return output, nil
}

// generateModels creates the models.py file with Pydantic models
func (g *Generator) generateModels(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	var buf bytes.Buffer

	// Header
	buf.WriteString("# Generated by Flux CMS SDK Generator\n")
	buf.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	buf.WriteString("# DO NOT EDIT - This file is auto-generated\n\n")

	// Imports
	buf.WriteString("from __future__ import annotations\n\n")
	buf.WriteString("from datetime import datetime, date\n")
	buf.WriteString("from typing import Any, Literal, Optional\n\n")
	buf.WriteString("from pydantic import BaseModel, Field\n\n")

	// Built-in types
	buf.WriteString(BuiltInTypes())

	// Generate enum classes (as Literal type aliases)
	for _, schema := range schemas {
		for _, enum := range schema.Enums {
			buf.WriteString(g.generateEnumType(&enum))
			buf.WriteString("\n\n")
		}
	}

	// Generate model for each schema
	for _, schema := range schemas {
		buf.WriteString(g.generateModel(schema, config))
		buf.WriteString("\n\n")

		// Create input model
		buf.WriteString(g.generateCreateInput(schema, config))
		buf.WriteString("\n\n")

		// Update input model (all fields optional)
		buf.WriteString(g.generateUpdateInput(schema, config))
		buf.WriteString("\n\n")
	}

	return buf.String(), nil
}

// generateEnumType creates a Python Literal type alias for an enum
func (g *Generator) generateEnumType(enum *parser.CompiledEnum) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("%s = Literal[", enum.Name))
	for i, value := range enum.Values {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(fmt.Sprintf("\"%s\"", value))
	}
	buf.WriteString("]")

	return buf.String()
}

// generateModel creates a Pydantic model for a schema
func (g *Generator) generateModel(schema *parser.CompiledSchema, _ sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("class %s(BaseModel):\n", typeName))
	buf.WriteString(fmt.Sprintf("    \"\"\"Model for %s schema.\"\"\"\n\n", schema.Name))

	if len(schema.Fields) == 0 {
		buf.WriteString("    pass\n")
		return buf.String()
	}

	for _, field := range schema.Fields {
		pyType := MapFieldTypeWithOptional(&field)
		fieldName := ToSnakeCase(field.Name)

		if !field.Required && !field.ArrayReq {
			buf.WriteString(fmt.Sprintf("    %s: %s = None\n", fieldName, pyType))
		} else {
			buf.WriteString(fmt.Sprintf("    %s: %s\n", fieldName, pyType))
		}
	}

	// Add model_config for camelCase alias support
	buf.WriteString("\n    model_config = {\"populate_by_name\": True}\n")

	return buf.String()
}

// generateCreateInput creates an input model for creating documents
func (g *Generator) generateCreateInput(schema *parser.CompiledSchema, _ sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("class Create%sInput(BaseModel):\n", typeName))
	buf.WriteString(fmt.Sprintf("    \"\"\"Input model for creating a %s.\"\"\"\n\n", schema.Name))

	if len(schema.Fields) == 0 {
		buf.WriteString("    pass\n")
		return buf.String()
	}

	for _, field := range schema.Fields {
		pyType := g.mapInputFieldType(&field)
		fieldName := ToSnakeCase(field.Name)

		if !field.Required && !field.ArrayReq {
			buf.WriteString(fmt.Sprintf("    %s: %s = None\n", fieldName, pyType))
		} else {
			buf.WriteString(fmt.Sprintf("    %s: %s\n", fieldName, pyType))
		}
	}

	return buf.String()
}

// generateUpdateInput creates an input model for updating documents
func (g *Generator) generateUpdateInput(schema *parser.CompiledSchema, _ sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)
	buf.WriteString(fmt.Sprintf("class Update%sInput(BaseModel):\n", typeName))
	buf.WriteString(fmt.Sprintf("    \"\"\"Input model for updating a %s. All fields optional.\"\"\"\n\n", schema.Name))

	if len(schema.Fields) == 0 {
		buf.WriteString("    pass\n")
		return buf.String()
	}

	for _, field := range schema.Fields {
		pyType := g.mapInputFieldType(&field)
		fieldName := ToSnakeCase(field.Name)
		if !strings.HasPrefix(pyType, "Optional[") {
			pyType = "Optional[" + pyType + "]"
		}
		buf.WriteString(fmt.Sprintf("    %s: %s = None\n", fieldName, pyType))
	}

	return buf.String()
}

// mapInputFieldType maps a field to its Python input type (relations become str IDs)
func (g *Generator) mapInputFieldType(field *parser.CompiledField) string {
	if field.IsRelation {
		if field.Array {
			return "list[str]"
		}
		if !field.Required {
			return "Optional[str]"
		}
		return "str"
	}
	return MapFieldTypeWithOptional(field)
}

// generateClient creates the client.py file with an httpx-based API client
func (g *Generator) generateClient(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Flux CMS SDK Generator\n")
	buf.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	buf.WriteString("# DO NOT EDIT - This file is auto-generated\n\n")

	buf.WriteString("from __future__ import annotations\n\n")
	buf.WriteString("from typing import Any, Optional\n\n")
	buf.WriteString("import httpx\n\n")

	// Import models
	buf.WriteString("from .models import (\n")
	for _, schema := range schemas {
		typeName := ToPascalCase(schema.Name)
		buf.WriteString(fmt.Sprintf("    %s,\n", typeName))
		buf.WriteString(fmt.Sprintf("    Create%sInput,\n", typeName))
		buf.WriteString(fmt.Sprintf("    Update%sInput,\n", typeName))
	}
	buf.WriteString(")\n\n\n")

	// Client class
	buf.WriteString("class FluxClient:\n")
	buf.WriteString("    \"\"\"Flux CMS API client.\"\"\"\n\n")

	buf.WriteString("    def __init__(\n")
	buf.WriteString("        self,\n")
	buf.WriteString("        base_url: str,\n")
	buf.WriteString("        api_key: Optional[str] = None,\n")
	buf.WriteString("        headers: Optional[dict[str, str]] = None,\n")
	buf.WriteString("    ) -> None:\n")

	baseURL := config.BaseURL
	if baseURL == "" {
		baseURL = "http://localhost:7080"
	}
	buf.WriteString(fmt.Sprintf("        self.base_url = base_url or \"%s\"\n", baseURL))
	buf.WriteString("        _headers = headers or {}\n")
	if config.TargetAPI == "content" {
		buf.WriteString("        if api_key:\n")
		buf.WriteString("            _headers[\"X-API-Key\"] = api_key\n")
	} else {
		buf.WriteString("        if api_key:\n")
		buf.WriteString("            _headers[\"Authorization\"] = f\"Bearer {api_key}\"\n")
	}
	buf.WriteString("        self._client = httpx.Client(base_url=self.base_url, headers=_headers)\n\n")

	buf.WriteString("    def close(self) -> None:\n")
	buf.WriteString("        \"\"\"Close the HTTP client.\"\"\"\n")
	buf.WriteString("        self._client.close()\n\n")

	buf.WriteString("    def __enter__(self) -> \"FluxClient\":\n")
	buf.WriteString("        return self\n\n")

	buf.WriteString("    def __exit__(self, *args: Any) -> None:\n")
	buf.WriteString("        self.close()\n\n")

	buf.WriteString("    def _request(self, method: str, path: str, **kwargs: Any) -> Any:\n")
	buf.WriteString("        response = self._client.request(method, path, **kwargs)\n")
	buf.WriteString("        response.raise_for_status()\n")
	buf.WriteString("        data = response.json()\n")
	buf.WriteString("        if isinstance(data, dict) and \"payload\" in data:\n")
	buf.WriteString("            return data[\"payload\"]\n")
	buf.WriteString("        return data\n\n")

	// Generate methods for each schema
	for _, schema := range schemas {
		typeName := ToPascalCase(schema.Name)
		apiID := schema.ApiID

		if config.TargetAPI == "content" {
			wsAPIID := config.WorkspaceAPIID
			buf.WriteString(fmt.Sprintf("    # --- %s ---\n\n", typeName))

			buf.WriteString(fmt.Sprintf("    def list_%s(self, page: int = 1, limit: int = 20, locale: str = \"en\") -> list[dict[str, Any]]:\n", ToSnakeCase(schema.Name)))
			buf.WriteString(fmt.Sprintf("        \"\"\"List published %s content.\"\"\"\n", schema.Name))
			buf.WriteString(fmt.Sprintf("        return self._request(\"GET\", \"/api/v1/content/%s/%s\", params={\"page\": page, \"limit\": limit, \"locale\": locale})\n\n", wsAPIID, apiID))

			buf.WriteString(fmt.Sprintf("    def get_%s_by_slug(self, slug: str) -> dict[str, Any]:\n", ToSnakeCase(schema.Name)))
			buf.WriteString(fmt.Sprintf("        \"\"\"Get published %s by slug.\"\"\"\n", schema.Name))
			buf.WriteString(fmt.Sprintf("        return self._request(\"GET\", f\"/api/v1/content/%s/%s/{slug}\")\n\n", wsAPIID, apiID))

			buf.WriteString(fmt.Sprintf("    def get_%s_by_id(self, id: str) -> dict[str, Any]:\n", ToSnakeCase(schema.Name)))
			buf.WriteString(fmt.Sprintf("        \"\"\"Get published %s by ID.\"\"\"\n", schema.Name))
			buf.WriteString(fmt.Sprintf("        return self._request(\"GET\", f\"/api/v1/content/%s/%s/id/{id}\")\n\n", wsAPIID, apiID))
		}
	}

	return buf.String(), nil
}

// generateInit creates the __init__.py barrel file
func (g *Generator) generateInit(config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Flux CMS SDK Generator\n")
	buf.WriteString("# DO NOT EDIT - This file is auto-generated\n\n")
	buf.WriteString("from .models import *  # noqa: F401, F403\n")

	if config.IncludeClient {
		buf.WriteString("from .client import FluxClient  # noqa: F401\n")
	}

	return buf.String()
}
