package typescript

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"

	"github.com/infrasutra/fsl/parser"
	"github.com/infrasutra/fsl/sdk"
)

// Generator implements SDK code generation for TypeScript
type Generator struct{}

// New creates a new TypeScript generator
func New() *Generator {
	return &Generator{}
}

// Language returns the target language name
func (g *Generator) Language() string {
	return "typescript"
}

// FileExtension returns the file extension for generated files
func (g *Generator) FileExtension() string {
	return ".ts"
}

// Generate produces TypeScript SDK code from compiled schemas
func (g *Generator) Generate(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (*sdk.GeneratedSDK, error) {
	output := &sdk.GeneratedSDK{
		Language:   "typescript",
		Files:      make(map[string]string),
		EntryPoint: "index.ts",
	}

	// Generate types file
	typesContent, err := g.generateTypes(schemas, config)
	if err != nil {
		return nil, fmt.Errorf("failed to generate types: %w", err)
	}
	output.Files["types.ts"] = typesContent

	// Generate client file if requested
	if config.IncludeClient {
		clientContent, err := g.generateClient(schemas, config)
		if err != nil {
			return nil, fmt.Errorf("failed to generate client: %w", err)
		}
		output.Files["client.ts"] = clientContent
	}

	// Generate index file
	indexContent := g.generateIndex(config)
	output.Files["index.ts"] = indexContent

	return output, nil
}

// generateTypes creates the types.ts file with all schema types
func (g *Generator) generateTypes(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	var buf bytes.Buffer

	// Header
	buf.WriteString("// Generated by Flux CMS SDK Generator\n")
	buf.WriteString(fmt.Sprintf("// Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	buf.WriteString("// DO NOT EDIT - This file is auto-generated\n\n")

	// Built-in types
	buf.WriteString(BuiltInTypes())
	buf.WriteString("\n")

	// Shared response types
	buf.WriteString(SharedResponseTypes())
	buf.WriteString("\n")

	// Generate enum types
	for _, schema := range schemas {
		for _, enum := range schema.Enums {
			buf.WriteString(g.generateEnumType(&enum))
			buf.WriteString("\n")
		}
	}

	// Generate slice-related component/union types before schema interfaces
	for _, schema := range schemas {
		buf.WriteString(g.generateSliceSupportTypes(schema, config))
	}

	// Generate interface for each schema
	for _, schema := range schemas {
		// Main type interface
		buf.WriteString(g.generateInterface(schema, config))
		buf.WriteString("\n")

		// Create input type (without id, createdAt, updatedAt)
		buf.WriteString(g.generateCreateInput(schema, config))
		buf.WriteString("\n")

		// Update input type (all fields optional)
		buf.WriteString(g.generateUpdateInput(schema, config))
		buf.WriteString("\n")

		// Filter type for querying
		buf.WriteString(g.generateFilterType(schema, config))
		buf.WriteString("\n")

		// Response aliases
		buf.WriteString(g.generateSchemaAliases(schema))
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

// generateEnumType creates a TypeScript union type for an enum
func (g *Generator) generateEnumType(enum *parser.CompiledEnum) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("export type %s = ", enum.Name))

	for i, value := range enum.Values {
		if i > 0 {
			buf.WriteString(" | ")
		}
		buf.WriteString(fmt.Sprintf("\"%s\"", value))
	}

	buf.WriteString(";\n")

	// Also export array of values for runtime validation
	buf.WriteString(fmt.Sprintf("export const %sValues = [", enum.Name))
	for i, value := range enum.Values {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(fmt.Sprintf("\"%s\"", value))
	}
	buf.WriteString("] as const;\n")

	return buf.String()
}

// generateInterface creates a TypeScript interface for a schema
func (g *Generator) generateInterface(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export interface %s {\n", typeName))

	// User-defined fields
	for _, field := range schema.Fields {
		tsType := g.mapFieldTypeWithNullability(schema, &field, config.StrictNullChecks)
		optionalMarker := ""
		if !field.Required && !field.ArrayReq {
			optionalMarker = "?"
		}
		buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", field.Name, optionalMarker, tsType))
	}

	buf.WriteString("}\n")

	return buf.String()
}

// generateCreateInput creates an input type for creating documents
func (g *Generator) generateCreateInput(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export interface Create%sInput {\n", typeName))

	for _, field := range schema.Fields {
		isOptional := !field.Required && !field.ArrayReq
		tsType := g.mapInputFieldType(schema, &field, config.StrictNullChecks, isOptional)
		optionalMarker := ""
		if isOptional {
			optionalMarker = "?"
		}
		buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", field.Name, optionalMarker, tsType))
	}

	buf.WriteString("}\n")

	return buf.String()
}

// generateUpdateInput creates an input type for updating documents
func (g *Generator) generateUpdateInput(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export interface Update%sInput {\n", typeName))

	for _, field := range schema.Fields {
		tsType := g.mapInputFieldType(schema, &field, config.StrictNullChecks, true)
		buf.WriteString(fmt.Sprintf("  %s?: %s;\n", field.Name, tsType))
	}

	buf.WriteString("}\n")

	return buf.String()
}

// generateFilterType creates a filter type for querying documents
func (g *Generator) generateFilterType(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export interface %sFilter {\n", typeName))
	if config.TargetAPI == "content" {
		buf.WriteString("  page?: number;\n")
		buf.WriteString("  perPage?: number;\n")
		buf.WriteString("  locale?: string;\n")
		buf.WriteString("  createdAfter?: string;\n")
		buf.WriteString("  createdBefore?: string;\n")
		buf.WriteString("  sortBy?: string;\n")
		buf.WriteString("  sortOrder?: 'asc' | 'desc';\n")
	} else {
		buf.WriteString("  limit?: number;\n")
		buf.WriteString("  offset?: number;\n")
		buf.WriteString("  status?: 'draft' | 'published' | 'archived';\n")
		buf.WriteString("  sort?: string;\n")
	}
	buf.WriteString("}\n")

	return buf.String()
}

func mapInputFieldType(field *parser.CompiledField, strictNullChecks, allowNull bool) string {
	tsType := MapFieldType(field)
	if field.IsRelation {
		if field.Array {
			tsType = "string[]"
		} else {
			tsType = "string"
		}
	}
	if allowNull && strictNullChecks {
		tsType = tsType + " | null"
	}
	return tsType
}

func (g *Generator) mapFieldTypeWithNullability(schema *parser.CompiledSchema, field *parser.CompiledField, strictNullChecks bool) string {
	if len(field.Slices) == 0 {
		return MapFieldTypeWithNullability(field, strictNullChecks)
	}

	baseType := g.sliceUnionTypeName(schema, field) + "[]"
	if !field.Required && strictNullChecks {
		return baseType + " | null"
	}

	return baseType
}

func (g *Generator) mapInputFieldType(schema *parser.CompiledSchema, field *parser.CompiledField, strictNullChecks, allowNull bool) string {
	if len(field.Slices) == 0 {
		return mapInputFieldType(field, strictNullChecks, allowNull)
	}

	tsType := g.sliceUnionTypeName(schema, field) + "[]"
	if allowNull && strictNullChecks {
		tsType += " | null"
	}

	return tsType
}

func (g *Generator) generateSliceSupportTypes(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	componentByName := make(map[string]*parser.CompiledComponent, len(schema.Components))
	for i := range schema.Components {
		component := &schema.Components[i]
		componentByName[component.Name] = component
	}

	emittedComponents := map[string]bool{}

	for _, field := range schema.Fields {
		if len(field.Slices) == 0 {
			continue
		}

		for _, slice := range field.Slices {
			component, ok := componentByName[slice.Schema]
			if !ok {
				continue
			}

			componentTypeName := g.sliceComponentTypeName(schema, slice.Schema)
			if emittedComponents[componentTypeName] {
				continue
			}

			emittedComponents[componentTypeName] = true
			buf.WriteString(fmt.Sprintf("export interface %s {\n", componentTypeName))
			for _, componentField := range component.Fields {
				tsType := MapFieldTypeWithNullability(&componentField, config.StrictNullChecks)
				optionalMarker := ""
				if !componentField.Required && !componentField.ArrayReq {
					optionalMarker = "?"
				}
				buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", componentField.Name, optionalMarker, tsType))
			}
			buf.WriteString("}\n\n")
		}

		unionTypeName := g.sliceUnionTypeName(schema, &field)
		buf.WriteString(fmt.Sprintf("export type %s =\n", unionTypeName))
		for idx, slice := range field.Slices {
			separator := " |"
			if idx == len(field.Slices)-1 {
				separator = ";"
			}

			buf.WriteString(fmt.Sprintf("  { type: \"%s\"; data: %s; variation?: string | null }%s\n",
				slice.Type,
				g.sliceComponentTypeName(schema, slice.Schema),
				separator,
			))
		}
		buf.WriteString("\n")
	}

	return buf.String()
}

func (g *Generator) sliceUnionTypeName(schema *parser.CompiledSchema, field *parser.CompiledField) string {
	return ToPascalCase(schema.Name) + ToPascalCase(field.Name) + "Slice"
}

func (g *Generator) sliceComponentTypeName(schema *parser.CompiledSchema, componentName string) string {
	return ToPascalCase(schema.Name) + ToPascalCase(componentName)
}

// generateSchemaAliases creates response type aliases per schema
func (g *Generator) generateSchemaAliases(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export type %sDocument = DocumentResponse<%s>;\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("export type %sListResponse = DocumentListResponse;\n", typeName))
	buf.WriteString(fmt.Sprintf("export type %sContentItem = ContentItem<%s>;\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("export type %sContentListResponse = ContentListResponse<%s>;\n", typeName, typeName))

	return buf.String()
}

// generateClient creates the API client code
func (g *Generator) generateClient(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	funcs := template.FuncMap{
		"pascal": ToPascalCase,
		"camel":  ToCamelCase,
		"lower":  strings.ToLower,
	}

	tmpl, err := template.New("client").Funcs(funcs).Parse(clientTemplate)
	if err != nil {
		return "", err
	}

	data := struct {
		BaseURL        string
		WorkspaceID    string
		ProjectID      string
		WorkspaceAPIID string
		TargetAPI      string
		Client         string
		Schemas        []*parser.CompiledSchema
		Timestamp      string
	}{
		BaseURL:        config.BaseURL,
		WorkspaceID:    config.WorkspaceID,
		ProjectID:      config.ProjectID,
		WorkspaceAPIID: config.WorkspaceAPIID,
		TargetAPI:      config.TargetAPI,
		Client:         config.Client,
		Schemas:        schemas,
		Timestamp:      time.Now().UTC().Format(time.RFC3339),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// generateIndex creates the index.ts barrel file
func (g *Generator) generateIndex(config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	buf.WriteString("// Generated by Flux CMS SDK Generator\n")
	buf.WriteString("// DO NOT EDIT - This file is auto-generated\n\n")

	buf.WriteString("export * from './types';\n")

	if config.IncludeClient {
		buf.WriteString("export * from './client';\n")
	}

	return buf.String()
}

// Client template for API client generation
var clientTemplate = `// Generated by Flux CMS SDK Generator
// Generated at: {{.Timestamp}}
// DO NOT EDIT - This file is auto-generated

{{- if eq .Client "axios" }}
import axios from 'axios';
{{- end }}
import type {
{{- range .Schemas }}
{{- if eq $.TargetAPI "cms" }}
  Create{{ .Name | pascal }}Input,
  Update{{ .Name | pascal }}Input,
  {{ .Name | pascal }}Filter,
  {{ .Name | pascal }}Document,
  {{ .Name | pascal }}ListResponse,
{{- else }}
  {{ .Name | pascal }}Filter,
  {{ .Name | pascal }}ContentItem,
  {{ .Name | pascal }}ContentListResponse,
{{- end }}
{{- end }}
} from './types';

export interface FluxClientConfig {
  baseURL: string;
  apiKey?: string;
  headers?: Record<string, string>;
}

export class FluxClient {
  private config: FluxClientConfig;
{{- if eq .TargetAPI "content" }}
  private workspaceApiId: string;
{{- else }}
  private projectId: string;
{{- end }}

{{- if eq .TargetAPI "content" }}
  constructor(config: FluxClientConfig, workspaceApiId: string = '{{.WorkspaceAPIID}}') {
{{- else }}
  constructor(config: FluxClientConfig, projectId: string = '{{.ProjectID}}') {
{{- end }}
    this.config = {
      baseURL: config.baseURL || '{{.BaseURL}}',
      ...config,
    };
{{- if eq .TargetAPI "content" }}
    this.workspaceApiId = workspaceApiId;
{{- else }}
    this.projectId = projectId;
{{- end }}
  }

  private async request<T>(
    method: string,
    path: string,
    body?: unknown
  ): Promise<T> {
    const url = ` + "`${this.config.baseURL}${path}`" + `;
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.config.headers,
    };

{{- if eq .TargetAPI "cms" }}
    if (this.config.apiKey) {
      headers['Authorization'] = ` + "`Bearer ${this.config.apiKey}`" + `;
    }
{{- else if eq .TargetAPI "content" }}
    if (this.config.apiKey) {
      headers['X-API-Key'] = this.config.apiKey;
    }
{{- end }}

{{- if eq .Client "axios" }}
    const response = await axios.request({
      method,
      url,
      headers,
      data: body,
    });

    const data = response.data;
{{- else }}
    const response = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.message || ` + "`HTTP ${response.status}`" + `);
    }

    const data = await response.json();
{{- end }}
    if (data && typeof data === 'object' && 'payload' in data) {
      return (data as { payload: T }).payload;
    }
    return data as T;
  }

{{range .Schemas}}
  // {{.Name}} methods
  {{.ApiID}} = {
{{- if eq $.TargetAPI "content" }}
    list: (filter?: {{.Name | pascal}}Filter): Promise<{{.Name | pascal}}ContentListResponse> => {
      const params = new URLSearchParams();
      if (filter?.page) params.set('page', String(filter.page));
      if (filter?.perPage) params.set('per_page', String(filter.perPage));
      if (filter?.locale) params.set('locale', filter.locale);
      if (filter?.createdAfter) params.set('created_after', filter.createdAfter);
      if (filter?.createdBefore) params.set('created_before', filter.createdBefore);
      if (filter?.sortBy) params.set('sort_by', filter.sortBy);
      if (filter?.sortOrder) params.set('sort_order', filter.sortOrder);
      const query = params.toString();
      return this.request('GET', ` + "`/api/v1/content/${this.workspaceApiId}/{{.ApiID}}${query ? '?' + query : ''}`" + `);
    },

    getBySlug: (slug: string): Promise<{{.Name | pascal}}ContentItem> =>
      this.request('GET', ` + "`/api/v1/content/${this.workspaceApiId}/{{.ApiID}}/${slug}`" + `),

    getById: (id: string): Promise<{{.Name | pascal}}ContentItem> =>
      this.request('GET', ` + "`/api/v1/content/${this.workspaceApiId}/{{.ApiID}}/id/${id}`" + `),
{{- else }}
    get: (id: string): Promise<{{.Name | pascal}}Document> =>
      this.request('GET', ` + "`/api/v1/cms/projects/${this.projectId}/documents/${id}`" + `),

    list: (filter?: {{.Name | pascal}}Filter): Promise<{{.Name | pascal}}ListResponse> => {
      const params = new URLSearchParams();
      if (filter?.limit) params.set('limit', String(filter.limit));
      if (filter?.offset) params.set('offset', String(filter.offset));
      if (filter?.status) params.set('status', filter.status);
      if (filter?.sort) params.set('sort', filter.sort);
      const query = params.toString();
      return this.request('GET', ` + "`/api/v1/cms/projects/${this.projectId}/schemas/{{.SchemaID}}/documents${query ? '?' + query : ''}`" + `);
    },

    create: (data: Create{{.Name | pascal}}Input, options?: { slug?: string; locale?: string; message?: string }): Promise<{{.Name | pascal}}Document> =>
      this.request('POST', ` + "`/api/v1/cms/projects/${this.projectId}/schemas/{{.SchemaID}}/documents`" + `, { data, ...options }),

    update: (id: string, data: Update{{.Name | pascal}}Input, options?: { slug?: string; message?: string }): Promise<{{.Name | pascal}}Document> =>
      this.request('PUT', ` + "`/api/v1/cms/projects/${this.projectId}/documents/${id}`" + `, { data, ...options }),

    delete: (id: string): Promise<void> =>
      this.request('DELETE', ` + "`/api/v1/cms/projects/${this.projectId}/documents/${id}`" + `),

    publish: (id: string): Promise<{{.Name | pascal}}Document> =>
      this.request('POST', ` + "`/api/v1/cms/projects/${this.projectId}/documents/${id}/publish`" + `),

    archive: (id: string): Promise<{{.Name | pascal}}Document> =>
      this.request('POST', ` + "`/api/v1/cms/projects/${this.projectId}/documents/${id}/archive`" + `),
{{- end }}
  };
{{end}}
}
`

