package typescript

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"

	"github.com/infrasutra/fsl/parser"
	"github.com/infrasutra/fsl/sdk"
)

// Generator implements SDK code generation for TypeScript
type Generator struct{}

// New creates a new TypeScript generator
func New() *Generator {
	return &Generator{}
}

// Language returns the target language name
func (g *Generator) Language() string {
	return "typescript"
}

// FileExtension returns the file extension for generated files
func (g *Generator) FileExtension() string {
	return ".ts"
}

// Generate produces TypeScript SDK code from compiled schemas
func (g *Generator) Generate(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (*sdk.GeneratedSDK, error) {
	output := &sdk.GeneratedSDK{
		Language:   "typescript",
		Files:      make(map[string]string),
		EntryPoint: "index.ts",
	}

	typesContent, err := g.generateTypes(schemas, config)
	if err != nil {
		return nil, fmt.Errorf("failed to generate types: %w", err)
	}
	output.Files["types.ts"] = typesContent

	if config.IncludeClient {
		clientContent, err := g.generateClient(schemas, config)
		if err != nil {
			return nil, fmt.Errorf("failed to generate client: %w", err)
		}
		output.Files["client.ts"] = clientContent
	}

	indexContent := g.generateIndex(config)
	output.Files["index.ts"] = indexContent

	return output, nil
}

func (g *Generator) generateTypes(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("// Generated by Flux CMS SDK Generator\n")
	buf.WriteString(fmt.Sprintf("// Generated at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	buf.WriteString("// DO NOT EDIT - This file is auto-generated\n\n")

	buf.WriteString(BuiltInTypes())
	buf.WriteString("\n")

	buf.WriteString(SharedResponseTypes())
	buf.WriteString("\n")

	emitted := map[string]bool{}
	for _, schema := range schemas {
		for _, enum := range schema.Enums {
			key := enum.Name + "=" + strings.Join(enum.Values, "|")
			if emitted[key] {
				continue
			}
			emitted[key] = true
			buf.WriteString(g.generateEnumType(&enum))
			buf.WriteString("\n")
		}
	}

	for _, schema := range schemas {
		buf.WriteString(g.generateSliceSupportTypes(schema, config))
	}

	for _, schema := range schemas {

		buf.WriteString(g.generateInterface(schema, config))
		buf.WriteString("\n")

		buf.WriteString(g.generateCreateInput(schema, config))
		buf.WriteString("\n")

		buf.WriteString(g.generateUpdateInput(schema, config))
		buf.WriteString("\n")

		buf.WriteString(g.generateFilterType(schema, config))
		buf.WriteString("\n")

		buf.WriteString(g.generateSchemaAliases(schema))
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

func (g *Generator) generateEnumType(enum *parser.CompiledEnum) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("export type %s = ", enum.Name))

	for i, value := range enum.Values {
		if i > 0 {
			buf.WriteString(" | ")
		}
		buf.WriteString(fmt.Sprintf("\"%s\"", value))
	}

	buf.WriteString(";\n")

	buf.WriteString(fmt.Sprintf("export const %sValues = [", enum.Name))
	for i, value := range enum.Values {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(fmt.Sprintf("\"%s\"", value))
	}
	buf.WriteString("] as const;\n")

	return buf.String()
}

func (g *Generator) generateInterface(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export interface %s {\n", typeName))

	for _, field := range schema.Fields {
		tsType := g.mapFieldTypeWithNullability(schema, &field, config.StrictNullChecks)
		buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", field.Name, optionalMarker(&field), tsType))
	}

	buf.WriteString("}\n")

	return buf.String()
}

func optionalMarker(field *parser.CompiledField) string {
	if isOptionalField(field) {
		return "?"
	}
	return ""
}

func isOptionalField(field *parser.CompiledField) bool {
	if field.Array || len(field.Slices) > 0 {
		return !field.ArrayReq && !(len(field.Slices) > 0 && field.Required)
	}
	return !field.Required
}

func (g *Generator) generateCreateInput(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export interface Create%sInput {\n", typeName))

	for _, field := range schema.Fields {
		isOptional := isOptionalField(&field)
		tsType := g.mapInputFieldType(schema, &field, config.StrictNullChecks, isOptional)
		buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", field.Name, optionalMarker(&field), tsType))
	}

	buf.WriteString("}\n")

	return buf.String()
}

func (g *Generator) generateUpdateInput(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export interface Update%sInput {\n", typeName))

	for _, field := range schema.Fields {
		tsType := g.mapInputFieldType(schema, &field, config.StrictNullChecks, true)
		buf.WriteString(fmt.Sprintf("  %s?: %s;\n", field.Name, tsType))
	}

	buf.WriteString("}\n")

	return buf.String()
}

func (g *Generator) generateFilterType(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	if config.TargetAPI == "content" {
		buf.WriteString(fmt.Sprintf("export type %sFilter = ContentListOptions;\n", typeName))
		return buf.String()
	}
	buf.WriteString(fmt.Sprintf("export interface %sFilter {\n", typeName))
	{
		buf.WriteString("  limit?: number;\n")
		buf.WriteString("  offset?: number;\n")
		buf.WriteString("  status?: 'draft' | 'published' | 'archived';\n")
		buf.WriteString("  sort?: string;\n")
	}
	buf.WriteString("}\n")

	return buf.String()
}

func mapInputFieldType(field *parser.CompiledField, strictNullChecks, allowNull bool) string {
	tsType := MapFieldType(field)
	switch {
	case field.IsRelation && field.Array:
		tsType = "string[]"
	case field.IsRelation:
		tsType = "string"
	case field.Array && strings.Contains(tsType, "|"):
		tsType = "(" + tsType + ")[]"
	case field.Array:
		tsType += "[]"
	}
	if allowNull && strictNullChecks {
		tsType = tsType + " | null"
	}
	return tsType
}

func (g *Generator) mapFieldTypeWithNullability(schema *parser.CompiledSchema, field *parser.CompiledField, strictNullChecks bool) string {
	if len(field.Slices) == 0 {
		return MapFieldTypeWithNullability(field, strictNullChecks)
	}

	baseType := g.sliceUnionTypeName(schema, field) + "[]"
	if !field.Required && strictNullChecks {
		return baseType + " | null"
	}

	return baseType
}

func (g *Generator) mapInputFieldType(schema *parser.CompiledSchema, field *parser.CompiledField, strictNullChecks, allowNull bool) string {
	if len(field.Slices) == 0 {
		return mapInputFieldType(field, strictNullChecks, allowNull)
	}

	tsType := g.sliceUnionTypeName(schema, field) + "[]"
	if allowNull && strictNullChecks {
		tsType += " | null"
	}

	return tsType
}

func (g *Generator) generateSliceSupportTypes(schema *parser.CompiledSchema, config sdk.GeneratorConfig) string {
	var buf bytes.Buffer
	componentByName := make(map[string]*parser.CompiledComponent, len(schema.Components))
	for i := range schema.Components {
		componentByName[schema.Components[i].Name] = &schema.Components[i]
	}
	emitted := map[string]bool{}

	var emitUnion func(owner string, field *parser.CompiledField)
	emitComponent := func(name string) {
		typeName := g.sliceComponentTypeName(schema, name)
		component, ok := componentByName[name]
		if !ok || emitted[typeName] {
			return
		}
		emitted[typeName] = true
		for i := range component.Fields {
			if len(component.Fields[i].Slices) > 0 {
				emitUnion(name, &component.Fields[i])
			}
		}
		buf.WriteString(fmt.Sprintf("export interface %s {\n", typeName))
		for i := range component.Fields {
			field := &component.Fields[i]
			tsType := MapFieldTypeWithNullability(field, config.StrictNullChecks)
			if len(field.Slices) > 0 {
				tsType = g.nestedSliceUnionTypeName(schema, name, field) + "[]"
			}
			buf.WriteString(fmt.Sprintf("  %s%s: %s;\n", field.Name, optionalMarker(field), tsType))
		}
		buf.WriteString("}\n\n")
	}
	emitUnion = func(owner string, field *parser.CompiledField) {
		unionName := g.sliceUnionTypeName(schema, field)
		if owner != "" {
			unionName = g.nestedSliceUnionTypeName(schema, owner, field)
		}
		if emitted[unionName] {
			return
		}
		emitted[unionName] = true
		for _, slice := range field.Slices {
			emitComponent(slice.Schema)
		}
		buf.WriteString(fmt.Sprintf("export type %s =\n", unionName))
		for idx, slice := range field.Slices {
			separator := " |"
			if idx == len(field.Slices)-1 {
				separator = ";"
			}
			buf.WriteString(fmt.Sprintf("  { __id?: string; type: \"%s\"; data: %s; variation?: string | null }%s\n", slice.Type, g.sliceComponentTypeName(schema, slice.Schema), separator))
		}
		buf.WriteString("\n")
	}

	for i := range schema.Fields {
		if len(schema.Fields[i].Slices) > 0 {
			emitUnion("", &schema.Fields[i])
		}
	}
	return buf.String()
}

func (g *Generator) nestedSliceUnionTypeName(schema *parser.CompiledSchema, component string, field *parser.CompiledField) string {
	return ToPascalCase(schema.Name) + ToPascalCase(component) + ToPascalCase(field.Name) + "Slice"
}

func (g *Generator) sliceUnionTypeName(schema *parser.CompiledSchema, field *parser.CompiledField) string {
	return ToPascalCase(schema.Name) + ToPascalCase(field.Name) + "Slice"
}

func (g *Generator) sliceComponentTypeName(schema *parser.CompiledSchema, componentName string) string {
	return ToPascalCase(schema.Name) + ToPascalCase(componentName)
}

func (g *Generator) generateSchemaAliases(schema *parser.CompiledSchema) string {
	var buf bytes.Buffer

	typeName := ToPascalCase(schema.Name)

	buf.WriteString(fmt.Sprintf("export type %sDocument = DocumentResponse<%s>;\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("export type %sListResponse = DocumentListResponse;\n", typeName))
	buf.WriteString(fmt.Sprintf("export type %sContentItem = ContentItem<%s>;\n", typeName, typeName))
	buf.WriteString(fmt.Sprintf("export type %sContentListResponse = ContentListResponse<%s>;\n", typeName, typeName))

	return buf.String()
}

func (g *Generator) generateClient(schemas []*parser.CompiledSchema, config sdk.GeneratorConfig) (string, error) {
	funcs := template.FuncMap{
		"pascal": ToPascalCase,
		"camel":  ToCamelCase,
		"lower":  strings.ToLower,
	}

	tmpl, err := template.New("client").Funcs(funcs).Parse(clientTemplate)
	if err != nil {
		return "", err
	}

	data := struct {
		BaseURL        string
		WorkspaceID    string
		ProjectID      string
		WorkspaceAPIID string
		TargetAPI      string
		Client         string
		Schemas        []*parser.CompiledSchema
		Timestamp      string
	}{
		BaseURL:        config.BaseURL,
		WorkspaceID:    config.WorkspaceID,
		ProjectID:      config.ProjectID,
		WorkspaceAPIID: config.WorkspaceAPIID,
		TargetAPI:      config.TargetAPI,
		Client:         config.Client,
		Schemas:        schemas,
		Timestamp:      time.Now().UTC().Format(time.RFC3339),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (g *Generator) generateIndex(config sdk.GeneratorConfig) string {
	var buf bytes.Buffer

	buf.WriteString("// Generated by Flux CMS SDK Generator\n")
	buf.WriteString("// DO NOT EDIT - This file is auto-generated\n\n")

	buf.WriteString("export * from './types';\n")

	if config.IncludeClient {
		buf.WriteString("export * from './client';\n")
	}

	return buf.String()
}

var clientTemplate = `// Generated by Flux CMS SDK Generator
// Generated at: {{.Timestamp}}
// DO NOT EDIT - This file is auto-generated

{{- if eq .Client "axios" }}
import axios from 'axios';
{{- end }}
import type {
{{- range .Schemas }}
{{- if eq $.TargetAPI "cms" }}
  Create{{ .Name | pascal }}Input,
  Update{{ .Name | pascal }}Input,
  {{ .Name | pascal }}Filter,
  {{ .Name | pascal }}Document,
  {{ .Name | pascal }}ListResponse,
{{- else }}
  {{ .Name | pascal }}ContentItem,
  {{ .Name | pascal }}ContentListResponse,
{{- end }}
{{- end }}
{{- if ne .TargetAPI "cms" }}
  ContentListOptions,
{{- end }}
} from './types';

export interface FluxClientConfig {
  baseURL: string;
  apiKey?: string;
  headers?: Record<string, string>;
}

export class FluxClient {
  private config: FluxClientConfig;
{{- if ne .TargetAPI "content" }}
  private projectId: string;
{{- end }}

{{- if eq .TargetAPI "content" }}
  constructor(config: FluxClientConfig) {
{{- else }}
  constructor(config: FluxClientConfig, projectId: string = '{{.ProjectID}}') {
{{- end }}
    this.config = {
      ...config,
      baseURL: config.baseURL || '{{.BaseURL}}',
    };
{{- if ne .TargetAPI "content" }}
    this.projectId = projectId;
{{- end }}
  }

  private async request<T>(
    method: string,
    path: string,
    body?: unknown,
    unwrap = true
  ): Promise<T> {
    const url = ` + "`${this.config.baseURL}${path}`" + `;
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.config.headers,
    };

{{- if eq .TargetAPI "cms" }}
    if (this.config.apiKey) {
      headers['Authorization'] = ` + "`Bearer ${this.config.apiKey}`" + `;
    }
{{- else if eq .TargetAPI "content" }}
    if (this.config.apiKey) {
      headers['X-API-Key'] = this.config.apiKey;
    }
{{- end }}

{{- if eq .Client "axios" }}
    const response = await axios.request({
      method,
      url,
      headers,
      data: body,
    });

    const data = response.data;
{{- else }}
    const response = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.message || ` + "`HTTP ${response.status}`" + `);
    }

    const data = await response.json();
{{- end }}
    if (unwrap && data && typeof data === 'object' && 'payload' in data) {
      return (data as { payload: T }).payload;
    }
    return data as T;
  }

{{range .Schemas}}
  // {{.Name}} methods
  {{.ApiID}} = {
{{- if eq $.TargetAPI "content" }}
    list: (options?: ContentListOptions): Promise<{{.Name | pascal}}ContentListResponse> => {
      const params = new URLSearchParams();
      if (options?.page) params.set('page', String(options.page));
      if (options?.limit) params.set('limit', String(options.limit));
      if (options?.locale) params.set('locale', options.locale);
      if (options?.sort) params.set('sort', options.sort);
      for (const filter of options?.filter ?? []) params.append('filter', filter);
      if (options?.fields?.length) params.set('fields', options.fields.join(','));
      if (options?.include?.length) params.set('include', options.include.join(','));
      const query = params.toString();
      return this.request('GET', ` + "`/api/v1/content/{{.ApiID}}${query ? '?' + query : ''}`" + `, undefined, false);
    },

    getBySlug: (slug: string, options?: { locale?: string; include?: string[] }): Promise<{{.Name | pascal}}ContentItem> => {
      const params = new URLSearchParams();
      if (options?.locale) params.set('locale', options.locale);
      if (options?.include?.length) params.set('include', options.include.join(','));
      const query = params.toString();
      return this.request('GET', ` + "`/api/v1/content/{{.ApiID}}/${encodeURIComponent(slug)}${query ? '?' + query : ''}`" + `);
    },

    getById: (id: string, options?: { include?: string[] }): Promise<{{.Name | pascal}}ContentItem> => {
      const query = options?.include?.length ? '?include=' + encodeURIComponent(options.include.join(',')) : '';
      return this.request('GET', ` + "`/api/v1/content/{{.ApiID}}/id/${id}${query}`" + `);
    },
{{- else }}
    get: (id: string): Promise<{{.Name | pascal}}Document> =>
      this.request('GET', ` + "`/api/v1/projects/${this.projectId}/documents/${id}`" + `),

    list: (filter?: {{.Name | pascal}}Filter): Promise<{{.Name | pascal}}ListResponse> => {
      const params = new URLSearchParams();
      if (filter?.limit) params.set('limit', String(filter.limit));
      if (filter?.offset) params.set('offset', String(filter.offset));
      if (filter?.status) params.set('status', filter.status);
      if (filter?.sort) params.set('sort', filter.sort);
      const query = params.toString();
      return this.request('GET', ` + "`/api/v1/projects/${this.projectId}/schemas/{{.SchemaID}}/documents${query ? '?' + query : ''}`" + `);
    },

    create: (data: Create{{.Name | pascal}}Input, options?: { slug?: string; locale?: string; message?: string }): Promise<{{.Name | pascal}}Document> =>
      this.request('POST', ` + "`/api/v1/projects/${this.projectId}/schemas/{{.SchemaID}}/documents`" + `, { data, ...options }),

    update: (id: string, data: Update{{.Name | pascal}}Input, options?: { slug?: string; message?: string }): Promise<{{.Name | pascal}}Document> =>
      this.request('PUT', ` + "`/api/v1/projects/${this.projectId}/documents/${id}`" + `, { data, ...options }),

    delete: (id: string): Promise<void> =>
      this.request('DELETE', ` + "`/api/v1/projects/${this.projectId}/documents/${id}`" + `),

    publish: (id: string): Promise<{{.Name | pascal}}Document> =>
      this.request('POST', ` + "`/api/v1/projects/${this.projectId}/documents/${id}/publish`" + `),

    archive: (id: string): Promise<{{.Name | pascal}}Document> =>
      this.request('POST', ` + "`/api/v1/projects/${this.projectId}/documents/${id}/archive`" + `),
{{- end }}
  };
{{end}}
}
`
